### PR TITLE
3.9

### PR DESCRIPTION
**Pull request by chenxi050402**
Fixes issue #214.
Fixes issue #198 (sort of).

### CODE REVIEW

**Comment by chenxi050402** [comment]
Ready to merge.

**Comment by Bentroen** [comment]
Nice!! Thank you for fixing the stuff I pointed out. It's now much better overall :)
There are still some things I'd like to polish before merging. For the sake of completeness, I'll add them to this pull request over the next few days, instead of merging right away. (I need to acquire the habit of using one pull request per feature anyway, haha!)

**Comment by Bentroen** [comment]
I really like how the changes are looking so far! Here's a few additional improvements I'd suggest:

- [ ] I see you added a 'Back' arrow on the Preferences. We should keep the OK button at the bottom though. Themes should (mostly) only change the appearance and not where you must click to perform a certain action.
- [ ] I like the idea you're trying to convey with the layer lock icon; however, I'd still rather go with a padlock since the feature is called 'layer lock'. Also, it looks too similar to the volume icon and is not consistent with the existing themes.
- [ ] Having duplicate code for the Preferences window is very cumbersome, making it difficult to maintain. In one instance, specifically the 'Check for updates' toggle, there are now eight similar but slightly different lines responsible for drawing it — when a simple rearrangement in the code layout could keep it to a single one. I'll rework the Preferences a bit and try to fix this.
- [ ] The border surrounding the note block area is a bit off — there's a 1px gap between both the marker head and the bottom scrollbar. (Perhaps it could also use a softer color?)
- [ ] Bold font is missing in some places, like the titles in each released version's list of changes.
- [ ] When hovering web links, the font becomes gray. A lighter shade of blue would probably look better.
- [ ] The tempo edit window could be opened by clicking the tempo box instead of from the Edit menu. The menu option could also be removed.
- [ ] Entering a non-numeric value on the tempo causes an issue.
- [ ] Edge scrolling when dragging a selection is faster depending on FPS.
- [ ] Sound count is updated far too often on higher FPS.

I'd really like to ship a dark version of the Fluent theme as well. Let me know if you'd be able to work on it; otherwise, I'll give it a shot. :)

**Comment by chenxi050402** [comment]
It's better to test working and useable before committing to avoid conflicts

**Comment by chenxi050402** [comment]
About the url text, the Fluent design format shows that when hovering on URL or hyperlinks, the text becomes gray.

**Comment by chenxi050402** [comment]
merged my experimental branch into this because why not and also no more conflicts

**Comment by chenxi050402** [comment]
Alt + Enter to fullscreen like most games
Can be useful for recording on 1080p screens

**Comment by Bentroen** [comment]
I must say, I'm delighted by what you have done so far. Particularly, the whole Fluent theme(s!), the music player mode, and the accent color picker must've been REALLY tricky to implement, given the piles and piles of spaghetti code that this program consists of. :P
It's never much to say, thank you for your efforts! :)

While I'd love to keep seeing further improvements, we've already got a rich set of features ready for the next version. So I think it'd be wise to withhold from adding new features, at least for a while, and focus on polishing the existing ones so we can wrap up the next version.

I'm compiling a (hopefully) final list of changes that would improve code readability, integration of new features, and stability. Some of those you fixed in the meantime as I reviewed the changes; some I've been working on myself; and some can (should) be further discussed prior to release. For completeness, I'll post the full list and check the stuff that's out of the way. In any case, we should be closer than ever to 3.9 now!

**Comment by Bentroen** [comment]
My original list was 90% fixed by now, so there's no point in putting it here lol. There's just a couple of easy fixes to do before we release! Would be great if you could work on some of these; if not, I can work on it over the next few days :)

- Allow closing Preferences with Ctrl + P as well
- Layer names are slightly higher than the hint text (Layer 1, 2, etc.). Try to make them aligned if possible!
- When Ctrl is pressed, the mouse cursor could be changed to something else to indicate that note blocks may be selected.
- Add a toggle for the Acrylic effect, for performance on lower-end machines. (Maybe for the window rising animation/fade/dark as well)
- In the light Fluent theme, is the window shadow supposed to be white? (It looks sort of like a glow xD, perhaps it could be darker as in the dark mode)
- Remove the Dialog extension from the project, since we are no longer using it. (Reduces the executable size)
- Make the Discord ping less often (once every ~5 seconds), instead of every frame, to avoid excessive pings?
- When editing a text box (for example in Song properties), the mouse flashes between an arrow and cursor very fast
- Popups from dark mode, interface sound & blackout mode appear when hovering options in the theme dropdown
- Consider changing the unlimited FPS option to 240? Reasons: 1) it's not really "unlimited", it's just set to a really high value; 2) it forces GameMaker to draw thousands of frames, which it will never be able to reach, and 3) it causes a big impact on performance anyway, which is unnecessary, considering a value like 240 would have the same effect.

Let me know what you think!

**Comment by Bentroen** [comment]
Hi! I see an immediate issue with the code for writing UTF-8 strings: the value you're writing before the string is the length of the string itself, not of the encoded data. This makes it more difficult to parse the NBS file, as parsers won't be able to read the string contents in advance.

I see three ways of fixing this: 
  1) precalculate the length of the data based on the characters (more expensive and requires more code);
  2) after writing the string, seek the buffer to the position of the length value and rewrite it ("dirty");
  3) write the data to a temporary variable, and **only write it to the buffer at the end** -- at this point you'll know the length of the encoded data, so you can write it to the actual buffer, then write the data itself (cleanest option).

Since changing the fundamental structure of an NBS file is such a risky change, I'd like to postpone the format change to a later version, until we can both: 1) make sure that the code is absolutely, 100% fail-proof and reliable, and 2) make the format as future-proof as we can.

Changing a widely-adopted format has numerous consequences. Getting anything wrong implies generating broken NBS files, which means every NBS parser in existence will have to be updated to deal with wrong data. Since this has a lot of potential to go wrong, I'd like to make sure we get it absolutely right.

Additionally, the NBS format has been very unstable since the beginning of OpenNBS -- to this day, many parsers haven't been able to catch up with the latest changes, or have even given up on staying up-to-date. Hypixel, for example, is still stuck on version 3. Every file structure change breaks the format for existing parsers, and I'd like to do something to change this -- this way, NBS version 6 may be the last one that breaks compatibility in a major way.

Finally, postponing the format change will allow us to focus on bugs that may arise from all the additions in that version, making our workload a bit easier. Despite UTF-8 support being a long due change, I don't see the need to rush this feature. :)

**Comment by miclol** [comment]
@Bentroen (Is this why [pynbs](https://github.com/vberlier/pynbs) not properly reading NBS files)

**Comment by Bentroen** [comment]
> @Bentroen (Is this why [pynbs](https://github.com/vberlier/pynbs) not properly reading NBS files)

@miclol Not really! This format hasn't launched officially yet, however, it aims to fix exactly the problem you're encountering in pynbs (special characters not being encoded properly).
Since it's a delicate change, we'll release those changes later so we have more time to properly develop and test them.

(context: vberlier/pynbs#3)

**Comment by Bentroen** [comment]
Since [Realtime Blur](https://forum.yoyogames.com/index.php?threads/realtime-gaussian-blur-shader-pause-menu-gms-1-4-and-gms-2-3.81005/), the extension used for the Acrylic and Mica effects, is a paid extension, it wouldn't be ethical to publish its source code on the repository, as this would enable anyone who cloned the project to obtain the extension for free.

In order to remove its source code from the repository, I did an interactive rebase editing commit 89f3da4656dc7ee78941db5ee61cade838515080 (new hash) to remove the affected files. During development, these files were added to `.gitignore` (d08a9cd11540a2c5020861403c6cb6b9952548b0) and eventually deleted (cdd401774c64397b575042dc5d07a8a57a4e67f7 -- of course this commit no longer removes any files because they're now gone, so the commit message no longer makes sense). However, without the cleanup, the files would remain in the repository history, which would still allow access to the source code.

To allow the project to work even with the extension files missing, commit 634b3835e9e3f3446a5cddc52c333f520e176ed2 introduced a script, [`blur_scripts_alt.gml`](https://github.com/HielkeMinecraft/OpenNoteBlockStudio/blob/634b3835e9e3f3446a5cddc52c333f520e176ed2/scripts/blur_scripts_alt/blur_scripts_alt.gml), which acts as a wrapper to the functions defined in the extension. This way, when the files are absent they just return placeholder values that allow the program to run without the blur effect, but still showing transparency. Simply deleting the files would cause the program to crash otherwise.

This way, anyone who clones the repository will be able to run the program as normal. However, in order for the blur effect to work, a copy of the extension must be placed in the correct spot. For production releases, whoever builds the version ***must make sure to load the files correctly*** (this will likely be me, so consider this a note to self :D). For record, a list of the affected files is kept below:

<details>
<summary>Affected files:</summary>

```
shaders/blur_realtime/blur_realtime.fsh
shaders/blur_realtime/blur_realtime.vsh
shaders/blur_realtime/blur_realtime.yy
shaders/blur_static/blur_static.fsh
shaders/blur_static/blur_static.vsh
shaders/blur_static/blur_static.yy
scripts/blur_scripts/blur_scripts.gml
scripts/blur_scripts/blur_scripts.yy
```
</details>

One consequence of rebasing is that it rewrites the branch's history, which requires a force push. So if anyone besides me and @chenxi050402 has based work off this branch, make sure to clone it again!

With that, this PR should be (finally) ready to merge into the project! 🥳

**Pull request merged**
