### PR TITLE
Add cow_bell_1 sound

### LINKED ISSUE #171: Higher-octave cowbell sound not present in extra notes resource pack
**Describe the bug**
There is no `minecraft:block.note_block.cow_bell_1` sound in the resource pack

**To Reproduce**
1. Apply the extra notes resource pack from https://github.com/HielkeMinecraft/OpenNoteBlockStudio/blob/master/datafiles/Data/extranotes.zip
2. Run this command ingame: `/playsound minecraft:block.note_block.cow_bell_1 record @s ~ ~ ~`
3. Notice that you don't hear a sound because it does not exist. If you were to use `/playsound minecraft:block.note_block.cow_bell record @s ~ ~ ~` you would hear the normal cowbell.

**Expected behavior**
When you run `/playsound minecraft:block.note_block.cow_bell_1 record @s ~ ~ ~` you should hear a higher-pitched cowbell, similar to all of the other notes in the resource pack

**Screenshots**
image
(notice how we see "cow_bell" and "cow_bell_-1" but no "cow_bell_1"

### PR DESCRIPTION
**Pull request by FluxCapacitor2**
Fixes #171

I'm not sure why the file is smaller now, but it includes the new sound as well as its entry in `sounds.json`.

### CODE REVIEW

**Comment by FluxCapacitor2** [comment]
Wait, don't merge this yet, just realized I forgot the pack.mcmeta at the root folder

**Comment by Bentroen** [comment]
Ah okay, I'd completely have missed that too haha.
While you're at it, could you add a subtitle that's missing on to the `click_1` sound event?

**Comment by FluxCapacitor2** [comment]
I tried the new pack with a song ingame and it sounded like it was an octave too low. Are the higher `-1` sounds one octave or two octaves higher than the normal sound?

**Comment by Bentroen** [comment]
Oh yeah, two octaves. Since Minecraft goes one octave lower and one higher, you have to shift the sound up two octaves so its lowest pitch matches with the highest one of the default sound (if that makes sense).

**Comment by Bentroen** [comment]
Looking good! Thanks for the fix. :)

**Pull request merged**
